### ISSUE TITLE
在使用retrofit配合rxcache时，缓存模型转换失败

### ISSUE THREAD

**Issue by myqhit** [VictorAlbertos/RxCache#102]
在有网络的时候查询数据，缓存会默认保存在内存和磁盘，此时断开网络再查询，从内存中获取缓存，正常显示。但是如果app退出，下一次再从缓存中查询的时候是从磁盘上查询出来的，此时查询出来默认的数据结构变成LinkListTreeMap结构，转换成业务模型时失败java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.yixc.student.api.data.ResponsePublicKey

**Comment by JessYanCoding** [comment]
https://github.com/VictorAlbertos/RxCache/issues/73

**Comment by codesdt** [comment]
请问这个问题解决了吗？

**Comment by cocowobo** [comment]
注:下面的 ----替换成空格,github代码莫名的没格式,谁给我教一下
1.定义BaseJson类型_

public class BaseJson<T> implements Serializable {
------ private T------  body;
------ private int------code;
------ private String message;
------ private String exceptionDescription;
 }


2.在BaseJson的基础上可以在抽取T为集合的情况
public class BaseJsonImp<T> extends BaseJson<ArrayList<T>> implements Serializable {
----public BaseJsonImp( ArrayList<T> body, int code, String message, String exceptionDescription ) {
------ super ( body, code, message, exceptionDescription );
--- }
}
3.上面是基类,复制到基类文件夹下.
4.使用中,加入T为一个对象----评论对象先单独定义出来
/**
 * Description: 发布一条动态评论会返回的全部信息
 */
public class **CommentSaveInfo** {
------public int------commentId;------------   //文章评论ID
------public String username;------------//评论人姓名
------public String commentTime;------------ //评论时间
------public String commentContent;------  //评论内容
}
5.将评论对象和基类组装起来
/**
 * Description: 发布一条动态评论会返回的全部信息--封装类
 */
public class CommentSaveInfoImp extends BaseJson<# **CommentSaveInfo**> {
------public CommentSaveInfoImp( CommentSaveInfo body, int code, String message, String exceptionDescription ) {
----------super ( body, code, message, exceptionDescription );
------}
}
6.如果是T是个评论集合,这样和基类组装
/**
 * Description: 评论集合--封装类
 */
public class CommentSaveInfoListImp extends **BaseJsonImp**<CommentSaveInfo> {
------public CommentSaveInfoListImp( **ArrayList<CommentSaveInfo>**  body, int code, String message, String exceptionDescription ) {
----------super ( body, code, message, exceptionDescription );
------}
}
7.上面将所有类单独写出来,比较方便阅读和理解,还可以内部类完成,自我感觉看起来不舒服,上面的仅为参考,可自己思考实现
8,在retrofit请求中使用
------@POST (ConstantValue.discoverDel)  //评论删除
------Observable<**CommentSaveInfoImp**> discoverDel( @Query ("token") String token,
------------------------------------@Query ("userId") long userId,
------------------------------------@Query ("sign") String sign,
------------------------------------@Body RequestBody body );

**Comment by JessYanCoding** [comment]
兄弟, 作者是歪果仁, 用中文他是不会回你的, 这是基本的尊重
