### ISSUE TITLE
How to resolve other data formats？

### ISSUE THREAD

**Issue by XiongKe94** [VictorAlbertos/RxCache#113]

**Comment by XiongKe94** [comment]
For example, the data format is: XML, String,Probuff

**Comment by VictorAlbertos** [comment]
There is no such functionality on RxCache. RxCache uses [Jolyglot](https://github.com/VictorAlbertos/Jolyglot) as an agnostic layer to resolve against an specific json provider which the client provides. Therefore RxCache only support json serialization.
