### ISSUE TITLE
java.lang.annotation.IncompleteAnnotationException: dagger.Provides missing element type

### ISSUE THREAD

**Issue by chenbaige** [VictorAlbertos/RxCache#114]
dagger2+rxcache ：the following exception occurs

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
 com.google.common.util.concurrent.UncheckedExecutionException: java.lang.annotation.IncompleteAnnotationException: dagger.Provides missing element type

**Comment by VictorAlbertos** [comment]
Try to use the last version for both libraries (`1.8.3-2.x` -> RxCache, `2.14.1` -> Dagger2)
