### ISSUE TITLE
get data from RxCacheProviders withoutLoader exception

### ISSUE THREAD

**Issue by ghost** [VictorAlbertos/RxCache#117]
this is the exception
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 

find the following sample code : 

RxCacheRepository.RxCacheProviders()
                .getCachedData(ProviderHelper.<ArrayList<myDataObj>>withoutLoader(), new EvictProvider(false))
                .subscribe(new Consumer<Reply<ArrayList<myDataObj>>>() {
                    @Override
                    public void accept(Reply<ArrayList<myDataObj>> cacheReply) throws Exception {
                       Log.d("eee : ", cacheReply.toString());
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable e) throws Exception {
                        System.out.println("eee : " + e.getCause());
                    }
                });

and the provider interface : 
@LifeCache(duration = 5, timeUnit = TimeUnit.MINUTES)
    Observable<Reply<ArrayList<myDataObj>>> getCachedData
            (Observable<ArrayList<myDataObj>> dataArr, EvictProvider evictProvider );

whats wrong??

**Comment by VictorAlbertos** [comment]
`io.reactivex.exceptions.CompositeException: 2 exceptions occurred`

That says nothing. Take a look at every exception inside `CompositeException` to know the actual problem.

**Comment by ghost** [comment]
how can i get the cached data without Observable??
any tutorials or code sample works ??
