### ISSUE TITLE
EviceProvider doesnt work

### ISSUE THREAD

**Issue by AndroidBirdBoom** [VictorAlbertos/RxCache#128]
hi, i download RxCacheSamples-2.x and change code 'cacheProviders.getUsers(restApi.getUsers(idLastUserQueried, USERS_PER_PAGE), new DynamicKey(idLastUserQueried), new EvictProvider(false));' to 'cacheProviders.getUsers(restApi.getUsers(idLastUserQueried, USERS_PER_PAGE), new DynamicKey(idLastUserQueried), new EvictProvider(true));', and run demo, Caching is still in，doesnt deleted

**Comment by AndroidBirdBoom** [comment]
i see, only request new caches then old caches will  covered by new caches

**Comment by BryceLee** [comment]
It is bug,fixed version is here:https://github.com/BryceLee/RxCache
