### ISSUE TITLE
useExpiredDataIfLoaderNotAvailable(true)    issue 

### ISSUE THREAD

**Issue by XiFanYin** [VictorAlbertos/RxCache#131]
@VictorAlbertos   
condition：
                Local cache validity，
                initialize RxCache have alreadyadded‘useExpiredDataIfLoaderNotAvailable(true)  ’
                Verson：1.8.3-2.x
at this point：
      Request network error ，callback onNext（） show CacheData  is right，  meanwhile I need callback onError() show error  to user.  but onError() not executed .

later:
  again  Request network error， callback onError（），but  onNext（） not executed。 not executed CacheData clear. 

   I need everytime request network Error  ，callback onError（） and onNext（）。meanwhile  no clear Cache Data。

My code：

  ```
   //只要没网请求缓存就会提示用户没有网，有缓存就展示缓存，没缓存就不展示缓存
        CacheProviderUtils.getInstance().using(Provider.class)
                .getPatientInfo(Observable.empty(), new DynamicKey("eee"), new EvictDynamicKey(false))
                .compose(RxSchedulers.io_main())
                .compose(bindUntilEvent(ActivityEvent.DESTROY))
                .subscribe(new BaseObserver<Patient>() {
                    @Override
                    public void onNext(Patient patient) {

                        tv.setText(new Gson().toJson(patient) + "token必须保存起来，这样在上传图片和下载图片的时候，请求头里边需要放入的参数");
                        Log.e("BeanJson1", new Gson().toJson(patient));

                    }
                });

        //只要是没网就会抛出来错误CompositeException里边包裹两个错误：ConnectException 和RxCacheException
        //有网参数正确就是正常请求缓存，展示结果
        //有网参数错误就会报错来错误CompositeException里边包裹两个错误：ApiException和RxCacheException
        CacheProviderUtils.getInstance().using(Provider.class)
                .getPatientInfo(RetrofitUtil
                        .getInstance()
                        .create(API.class)                                                      //这里参数写成动态，防止数据呗驱除
                        .getPatientInfo(1, 2), new DynamicKey("eee"), new EvictDynamicKey(NetworkDetector.isNetworkReachable()))
                .compose(RxSchedulers.io_main())
                .compose(bindUntilEvent(ActivityEvent.DESTROY))
                .subscribe(new BaseObserver<Patient>() {
                    @Override
                    public void onNext(Patient patient) {

                        tv.setText(new Gson().toJson(patient) + "token必须保存起来，这样在上传图片和下载图片的时候，请求头里边需要放入的参数");
                        Log.e("BeanJson3", new Gson().toJson(patient));

                    }
                });


    }

```

Want to give a solution 。thank you~~

**Comment by XiFanYin** [comment]
@VictorAlbertos 

I know Rxjava2 Impossible to simultaneously callBack OnError（） and onNext（），And you might think I'm using it wrong the library。 but ,my need:  If  have a cache  must show，Whether the request is correct or not，And, if the request is wrong show Toast（） error message。
I have an idea：
overloaded function：useExpiredDataIfLoaderNotAvailable(Parameter 1 ，Parameter 2)，
Parameter 1：control Stream callBack onNext（） and onError（）。
Parameter 2：control  Clear the cache。

This gives the library more possibilities

 this library is very good ,but ,As a way of using this library, I would prefer the API to be more open and content to do anything

**Comment by XiFanYin** [comment]
Or you tell me how to modify the source code, I will modify by myself, thank you very much!

**Comment by qingmei2** [comment]
@XiFanYin 
这样可以不
```kotlin
serviceManager.userInfoService
                .getUserInfo(....)     // 网络请求
                .flatMap { it -> it.success()? 
                   Observable.just(it).compose {   
                        CacheProviderUtils.getInstance()
                                          .using(Provider.class)
                                          ...........
                   }    //请求成功处理缓存数据，交给RxCache缓存
                   :  Observable.just(it)    // 请求失败，不处理缓存，交给onNext中处理，UI显示错误信息
                }   
                .subscribeOn(schedulers.io())
                .observeOn(schedulers.ui())
                .subscribe { // ...  }
```

我的理解是，网络请求错误，自己处理，只有成功后，该缓存的数据才交给Rxcache缓存，RxCache只负责缓存的事，和网络请求的错误处理不应该有关联。

**Comment by XiFanYin** [comment]
老铁，果然可以~ 还是对Rx不熟悉啊！惭愧，惭愧

**Comment by xilost** [comment]
@qingmei2 "//请求成功处理缓存数据，交给RxCache缓存"  这里具体是怎么做的？手动将数据存入rxcache？
