### ISSUE TITLE
Caching always return LinkedTreeMap, not POJO that I defined

### ISSUE THREAD

**Issue by rizmaulana** [VictorAlbertos/RxCache#143]
I'm using retrofit + rxjava + rxcache
I want to create cache of specific request and I call using retrofit like this :

`fun getUserByCompany(companyId: Int?): Observable<BaseResponse<List<UserDto>>> = cacheManager.getUserByCompany(api.getUserByCompany(companyId), DynamicKey(companyId))`

But everytime the request call API, it return `List<UserDto>` but when the function call data from cache it always return `List<LinkedTreeMap>`.

**Comment by BryceLee** [comment]
You can cache Observable<List<UserDto>>. The project do not support Observable<BaseResponse<List<UserDto>>> yet.

**Comment by rizmaulana** [comment]
Thanks @BryceLee
