### ISSUE TITLE
Cache invalidation?

### ISSUE THREAD

**Issue by AdamCopperfield** [VictorAlbertos/RxCache#2]
I.e, you've got smth from GET `/api/smth/1` and then successfuly made PUT `/api/smth/1` or DELETE `/api/smth/1`. Is it possible to force invalidate cache from GET method?

**Comment by VictorAlbertos** [comment]
I think your question is more related to the way observables could be chained than RxCache itself ;)

I’m not an expert in reactive programming, but maybe this snippet of code could leads you to solve the question (If I have understood correctly).

```java
        retrofit.getUser(userId).flatmap(user -> 
        	retrofit.update(user))).flatmap(user -> 
				rxCache.getUser(Observable.just(user), () -> true).flatmap(user -> user);
```

Or if you need to request first the user from the cache.

```java
        rxCache.getUser(Observable.just(null), () -> false).map(user ->
			retrofit.updateUser(user.getId()).flatmap(user -> 
				rxCache.getUser(Observable.just(user), () -> true));
```
