### ISSUE TITLE
Few questions about rx-cache.

### ISSUE THREAD

**Issue by aurk** [VictorAlbertos/RxCache#22]
I have few questions about RX-cache.

1. Is it possible using RX-cache to filter data like fetch all live(live = 1) record.
2. How can we sort our object on the basis of some fields.

If this is possible, then how can we achieve this. Any example will be helpful for me.

Thanks in advance.

**Comment by VictorAlbertos** [comment]
Hi @aurk

> 1 Is it possible using RX-cache to filter data like fetch all live(live = 1) record.

You have two options, using DynamicKey when creating the provider

```java
getMocks(oMocks, new DynamicKey(live))
```
or iterating over them without using DynamicKey and filtering using [filter operator observable](http://reactivex.io/documentation/operators/filter.html)

```java
getMocks(oMocks)
    .flatMapIterable(mocks -> mocks)
    .filter(mock -> mock.isLive())
    .toList();

```

> 2 How can we sort our object on the basis of some fields.

Same answer as before. 

To perform add, update and delete operations, you can relay on the actionable API, which is explained on the README.md file.
