### ISSUE TITLE
Choose to not use Disk Cache

### ISSUE THREAD

**Issue by edwardhuerta** [VictorAlbertos/RxCache#23]
Hi,

So I'm about to use your framework but I see that using a Disk File for caching is mandatory. Can you make it NOT mandatory since I'm interested in your memory caching only.

This is useful with applications where we don't want to store cached data on the filesystem for security reasons.

Thanks!

**Comment by VictorAlbertos** [comment]
Hi.

No, that's not possible . You are welcome to perform a pull request with this functionality, with proper coverage of test of course. It would better to choose at level provider to use or not to use the persistence layer, instead as a global configuration. 

Using some new annotation, like `@SkipPersistende` 

But, what kind of data are you using that you are not able to write on disk? Like credentials or something?

**Comment by edwardhuerta** [comment]
Hi, I'm looking to store Bank information.

BTW, what happens when the device runs out of space? How does your
framework react? Because I can subclass the File class and set the space to
0L.

What do you think of that?

**Comment by VictorAlbertos** [comment]
There are some internal processes to evict the cached data when the amount of memory is near to reach the threshold (by default 100 mb).

You can set the `setMaxMBPersistenceCache` to 0. I think it would work, but I do not know for sure. 

```
new RxCache.Builder()
            .setMaxMBPersistenceCache(0)
            .persistence(cacheDir)
            .using(Providers.class);
```

**Comment by edwardhuerta** [comment]
I thought setMaxMBPersistenceCache was related to memory space, I was
referring to what would happen if the Disk ran out of space instead. (The
file we pass to the Builder). Because I'm interested in keeping the memory
cache active but not storing anything in the Disk.

**Comment by VictorAlbertos** [comment]
No, it is not. Please read the section related with this topic in the readme file.

> Configure the limit in megabytes for the data to be persisted

**Comment by edwardhuerta** [comment]
You are right. I set the value to zero and it does not persist to disk
anymore. Thanks!
On 12 May 2016 6:36 p.m., "Víctor Albertos" <notifications@github.com>
wrote:

No, it is not. Please read the section related with this topic in the
readme file.

Configure the limit in megabytes for the data to be persisted

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/VictorAlbertos/RxCache/issues/23#issuecomment-218813629>
