### ISSUE TITLE
Usage with Dagger 2.4

### ISSUE THREAD

**Issue by PavelSynek** [VictorAlbertos/RxCache#24]
When I try to use RxCache in project that uses the latest version of Dagger (2.4 at this point of time), it crashes with `java.lang.ClassNotFoundException: Didn't find class "dagger.internal.ScopedProvider" on path: DexPathList` because Google introduced some breaking changes in 2.3 (everything works with 2.2).

It is easily reproducible by including Dagger 2.4 into a project that uses RxCache.

The easy solution is to update your Dagger version to 2.4, but new Dagger releases can potentially break it again. The ideal solution for me as user would be to remove Dagger dependency from the library, but I guess that's not an option.

**Comment by VictorAlbertos** [comment]
Hi @PavelSynek 

I'm afraid removing Dagger is not an option right now. Although,  I've released a new version with your pull request merged. 

Try it please and let me know:
`compile "com.github.VictorAlbertos:RxCache:1.4.2"`

And thanks for your help ;)

**Comment by VictorAlbertos** [comment]
By the way, from where did you get the information about the issue? I have not able to find any resource about that.

**Comment by PavelSynek** [comment]
Thanks, everything works with 1.4.2!

I am using Dagger 2 in my pet project and I started seeing this weird crash on startup, after some poking I just downgraded to 2.1 thinking it was some Dagger bug unrelated to RxCache. Today I saw this Reddit post https://www.reddit.com/r/androiddev/comments/4jjmpe/dagger_2_change_logs/ and realized RxCache is also using Dagger.

**Comment by VictorAlbertos** [comment]
Hard to find ;) 

I'm glad it is working now.
