### ISSUE TITLE
Error: The Loader provided did not return any data and there is not data to load from the Cache

### ISSUE THREAD

**Issue by kraghu** [VictorAlbertos/RxCache#30]

**Comment by VictorAlbertos** [comment]
This error means that you are supplying an observable which subscription end with an exception or a null value, as long as the cache has not persisted any data previously. 

```java
getMocks(Observable.just(null)); //in the end, you are doing that.
```

**Comment by kraghu** [comment]
I figured this out . thanks for the help.

**Comment by sohnyi** [comment]
May you set ```minifyEnabled true``` and forgot to set **proguard rules**
