### ISSUE TITLE
the cache file unsafe ,would you like to add encryption algorithm for cache string

### ISSUE THREAD

**Issue by sungerk** [VictorAlbertos/RxCache#31]

**Comment by VictorAlbertos** [comment]
I have no experience working with encryption algorithm. Alt ought, I think this cold be a nice feature.

Would you be able to code the feature and submit a PR?

**Comment by VictorAlbertos** [comment]
Closing this due to lack of feedback.

**Comment by sungerk** [comment]
i'll try in my free time,but I've been so busy lately
