### ISSUE TITLE
custom cache key.

### ISSUE THREAD

**Issue by yanweimin7** [VictorAlbertos/RxCache#4]
why don't allow set cache key , currently use method name.

**Comment by VictorAlbertos** [comment]
RxCache’s api is designed to provide one inmutable blueprint (your interface), which exposes all your caching needs in a safety way.

But if you prefer or need to generate news keys at runtime, you can use the @DinamycKey annotation. Something like this: 

```java

//Declared in your interface provider
Observable<List<User>> handleUsers(@Loader Observable<List<User>> users, @DynamicKey String key);

//Using provider
public Observable<List<User>> getActiveUsers() {
	return rxCache.handleUsers(retrofit.getActiveUsers(), "activeUsers");
}

public Observable<List<User>> getBannedUsers() {
	return rxCache.handleUsers(retrofit.getBannedUsers(), "bannedUsers");
}
```
