### ISSUE TITLE
Question: How would one pre cache items?

### ISSUE THREAD

**Issue by tzake** [VictorAlbertos/RxCache#42]
Say I have an api that gets entities by id and a list of all entities.

I cache each entity by id, but when the application starts I would like to get all entities and cache each one by their id, thus when a get by id is called if the item has been pre cached then it is returned from cache, else it is loaded from the api by id.

Thanks!

**Comment by VictorAlbertos** [comment]
RxCache exposes the intents of your UI. Let's say that you have a paginated list, you will need an endpoint which provide pagination, if not you would be a little fucked up regarding what RxCache expects from your data xD

All the relations between objects should be hidden inside the own structure of the data retrieved from the repository.

But my point is, why do you need to cache all the items at the first time? Why don't you retrieved them when your UI requires to do it, and if it involves using pagination just use the pagination feature which RxCache provides?

**Comment by tzake** [comment]
I would like to fetch some initial data to limit the number of requests.

Nevermind, I'm still a noob in java and that includes rx, but I have managed to do it.

Thanks for the pagination tips.

**Comment by UserName-Haha** [comment]
> 我想获取一些初始数据来限制请求的数量。
> 
> 没关系，我仍然是java中的菜鸟，包括rx，但我已经设法做到了。
> 
> 感谢分页提示。

> 我想获取一些初始数据来限制请求的数量。
> 
> 没关系，我仍然是java中的菜鸟，包括rx，但我已经设法做到了。
> 
> 感谢分页提示。

Hello，How do you solve your problem?
