### ISSUE TITLE
Url or path in DynamicKey cause file not found exception

### ISSUE THREAD

**Issue by atkdev** [VictorAlbertos/RxCache#43]
If I specify some string with "/" symbol as DynamicKey value then RxCache generates own key based on this string and use it as part of path. But "/" symbol is not escaped or removed and it cause OnError when  RxCache trying to create the file which directory doesn't exists.

**Comment by VictorAlbertos** [comment]
Thanks @atkdev for reporting this. I'll definitely check it out this weekend.
