### ISSUE TITLE
No multiple Cache Interfaces with same Methode names possible

### ISSUE THREAD

**Issue by darenegade** [VictorAlbertos/RxCache#46]
Due to ProviderKey Generation it is not possible to have multiple cache interfaces with the same method names. 

It would be great if the interface name gets added to the ProviderKey.

```java
public interface UserCache {

  Observable<Reply<UserDto>> findOne(
      Observable<UserDto> oUser, DynamicKey userId, EvictDynamicKey update);

  Observable<Reply<List<UserDto>>> findAll(
      Observable<List<UserDto>> oUsers, EvictProvider update);

.... more methods
}
```
```java
public interface RouteCache {

  Observable<Reply<RouteDto>> findOne(
      Observable<RouteDto> oRoute, DynamicKey id, EvictDynamicKey update);

  Observable<Reply<List<RouteDto>>> findAll(
      Observable<List<RouteDto>> oRoutes, EvictProvider evictProvider);

...more methods
```

**Comment by VictorAlbertos** [comment]
Hi @darenegade 

Your request is not possible to implement because doing that RxCache will not longer maintain backward compatibility. If we use the name of the interface as part of the generated key, every previous data persisted won't be able to be retrieved because the new generated key won't match with the previous one.

Also, if at some point you need to use the Actionable API, only one interface is supported, so you will have problems using at the same time multiple instance interfaces running as proxies. RxCache is not design to be used in little interfaces, instead it expects that you define only one interface where you place all your caching needs.

**Comment by darenegade** [comment]
Ahh I see. I don't use the Actionable API for now and that's why I didn't knew it only supports one interface. That's a good point. I may give it a try some day. Although I'm not a friend of big interfaces with mixed up scopes. But everyone has his own programming style, right? 😄 

Thx for the quick and detailed reply. 👍

**Comment by VictorAlbertos** [comment]
@darenegade just to let you know that from 1.5.6 version RxCache allows the actionable API to be used with multiple providers interface ;)

**Comment by darenegade** [comment]
That's pretty cool. 😄 

How about now with the support of multiple providers with same method names?

Maybe only add the class name of the interface to the key of the second and upwards providers to maintain backward compatibility?!

But I don't really get the reason for backward compatibility in a cache. From my point of view a cache  should only hold data for a certain, maybe short, time. If the key names get changed for every interface it will result in loading some data again which shouldn't be such a great deal. Same as clearing the cache of the app. Or as clearing the cache of a browser, not a great deal. If an application holds a lot of necessary data which needs to stay within the application it should use a database instead of a cache.

**Comment by VictorAlbertos** [comment]
Sorry @darenegade but we can't do that. We have several apps which use RxCache to store the session of the user. So changing the way the key is created would end up on an automatically logout of the account. And I'm pretty sure most of the users of RxCache use it for store the user active session, among other data which just can't be assume as something disposable.
