### ISSUE TITLE
Evict without requesting new

### ISSUE THREAD

**Issue by PaulWoitaschek** [VictorAlbertos/RxCache#59]
Lets say I have 2 endpoints:
TrainingSummary and Trainings

Once I add a new training in the backend I want to evict the TrainingSummary for the day the training was uploaded. But I don't want to fetch new data instantly. Is that possible?

**Comment by VictorAlbertos** [comment]
I think what you are really asking is how to  evict data without using a loader.

RxCache was designed mainly to cache data wrapping calls, which means using a loader. But the "Actionable Api" was introduced to address this limitation. Take a look at the [docs](https://github.com/VictorAlbertos/RxCache/blob/master/README.md#actionable_section).

And if you feel that you need more flexibility regarding evicting actions, you can check [ReactiveCache](https://github.com/VictorAlbertos/ReactiveCache). RxCache and ReactiveCache share the same core, so any functionality available in RxCache is present too in ReactiveCache.
