### ISSUE TITLE
Stop api calls if call returns empty list

### ISSUE THREAD

**Issue by bmccorvey3** [VictorAlbertos/RxCache#61]
If a retrofit api call returns with an empty list, is it possible to store the empty list in the cache and have RxCache load this empty list instead of making more api calls? Currently, for a given api call, the cache keeps making this call until it has data to store

**Comment by VictorAlbertos** [comment]
This is the expected behaviour. I'm sorry if it doesn't suit your needs, but due to internal details and backward compatibility I can't change this behaviour.

**Comment by VictorAlbertos** [comment]
Feel free to reopen it :)
