### ISSUE TITLE
The observable value must be a List, otherwise an error will be thrown.

### ISSUE THREAD

**Issue by shs8023you** [VictorAlbertos/RxCache#65]
I use @ Actionable, RxProviders provide the method is this:
    @Actionable
    Observable<List<ChildEntity>> getChildRecommend(Observable<List<ChildEntity>> childEntity,
                                                    DynamicKey filterPage, EvictDynamicKey evictFilter);

Retrofit method is this:
    @FormUrlEncoded
    @POST("/")
    Observable<StatusEntity<List<ChildEntity>>> getChildRecommend(@FieldMap HashMap<String, String> params);

I call this：
CacheProvidersActionable.getChildRecommend(cacheProviders, new DynamicKey(makeKey(params)))
                .addFirst(childEntity)
                .toObservable()

Result The service does not see the server returning data?
I use the wrong way?

**Comment by VictorAlbertos** [comment]
Are you sure that `cacheProviders` variable returns any data at all? How is this variable defined?

**Comment by shs8023you** [comment]
Yes, it returns data.However, I do not see where it will call Retrofit.getChildRecommend
