### ISSUE TITLE
Couldn't convert result of type rx.Observable to io.reactivex.Observable

### ISSUE THREAD

**Issue by alouanemed** [VictorAlbertos/RxCache#67]
Hey,

When updating to RxJava 2, I am getting this error : 

`Caused by: java.lang.ClassCastException: Couldn't convert result of type rx.Observable to io.reactivex.Observable`

at this line of code (invoking the dataCached function), when retrieving data from the cache : 
```
Observable apiObservable = ...
Observable observableCache = providers.getArticles(apiObservable, new EvictDynamicKey(isload)).map(
            new dataCached<List<Article>>());
```
Here is dataCached function : 

```
    private  class dataCached<T> implements Function<Reply<T>, T> {
            @Override public T apply(Reply<T> httpResult) throws Exception  {
            return httpResult.getData();
        }
```

Anyway to solve this ? Thanks :)

**Comment by VictorAlbertos** [comment]
Check that the import of Observable type in the providers interface is io.reactivex.observable, or for that matter, the right one

**Comment by alouanemed** [comment]
Thank you Victor for your reponse :) ,
I did double check : I don't have `rx.Observable ` imported in my whole project :D, I got only this : `io.reactivex.observable`

**Comment by VictorAlbertos** [comment]
And are you imported the right version of RxCache??

**Comment by alouanemed** [comment]
Edit : 

it turns out the error is turns out that the erorr if from this line (getArticles() method) : 
```
Observable observableCache = providers.getArticles(apiObservable, new EvictDynamicKey(isload)).map(
            new dataCached<List<Article>>());
```

```
RxCache provider

public interface TheProvider {
    @LifeCache(duration = 7, timeUnit = TimeUnit.DAYS)
    Observable<Reply<List<Article>>> getArticles(Observable<List<Article>> items, EvictDynamicKey evictDynamicKey);
}
```

**Comment by alouanemed** [comment]
Yes, 

```
compile "com.github.VictorAlbertos.RxCache:runtime:1.6.8"
compile 'com.github.VictorAlbertos.Jolyglot:gson:0.0.3'
```

**Comment by VictorAlbertos** [comment]
That's for rxjava 1.x You need to use: 
compile "com.github.VictorAlbertos.RxCache:runtime:1.6.8-2.x"
Change the branch to 2.x in the repo in order to see the associated readme

**Comment by alouanemed** [comment]
Fixed Thanks :) .
