### ISSUE TITLE
EvictDynamicKey was provided but not was provided any DynamicKey

### ISSUE THREAD

**Issue by alouanemed** [VictorAlbertos/RxCache#71]
Hey, After updating to RxJava 2 and use the appropriate RxCache version,  I couldn't anymore make API requests,by using HttpLoggingInterceptor nothing happens when invoking "performGetQuiz" method..just an empty screen and logcat.

`.debug D/Interactor$1$override: java.lang.IllegalArgumentException: getCachedQuestions EvictDynamicKey was provided but not was provided any DynamicKey`

Code : https://gist.github.com/alouanemed/7aa9c2153fd80a31cfc74654743988a9

**Comment by VictorAlbertos** [comment]
Sorry @alouanemed. I have not time right now to investigate potential bugs. If you are able to narrow the problem and it is indeed a bug I'll be happy to fix it.

**Comment by alouanemed** [comment]
Hey Victor,

Update the code : `new DynamicKey("key"), new EvictDynamicKey(false)`

Thank you, fixed .
