### ISSUE TITLE
Data from 2 sources concat(cache, cloud)?

### ISSUE THREAD

**Issue by volser** [VictorAlbertos/RxCache#72]
How to get data from 2 sources if cache expired?

if cache not exists then return just network data.
if cache not expired then return just cache.
if cache expired then return Observable.concat(expired_cache_data, network_data)

? 

I want to display expired data while getting fresh

**Comment by VictorAlbertos** [comment]
> I want to display expired data while getting fresh

RxCache does not support this functionality. You need to add your own logic to achieve that.
