### ISSUE TITLE
RxCache not support generic paradigm

### ISSUE THREAD

**Issue by ml-bright** [VictorAlbertos/RxCache#73]
like this:

    class Response<T> {

        int code;

       T data;

     }

I want to cast to `Response<List<City>>` use the `T`

while throw exception `java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap`

**Comment by ml-bright** [comment]
I solved this problem use other method

before 

     Observable<List<City>> getHotCityList(Observable<Response<List<City>>> hotCitys, EvictProvider evictProvider);

change like this:

     Observable<List<City>> getHotCityList(Observable<String> hotCitys, EvictProvider evictProvider);

we just change `Observable<Response<List<City>>> hotCitys` to `Observable<String> hotCitys` use **retrofit**. 

the next step:

use rxjava `compose`  to `String -> Response<List<City>>`

    apiServiceCache.getHotCityList(stringObservable, new EvictProvider(false))
                .compose(ComposeString2List.newCompose(new TypeToken<Response<List<City>>>(){}))

ComposeString2List.java:
   
     public class ComposeString2List<T> implements Observable.Transformer<String, List<T>> {

         public TypeToken<Response<List<T>>> typeToken;

         public static ComposeString2List newCompose(TypeToken typeToken) {
            return new ComposeString2List(typeToken);
        }

        public ComposeString2List(TypeToken<Response<List<T>>> typeToken) {
            this.typeToken = typeToken;
        }

        @Override
         public Observable<List<T>> call(Observable<String> responseObservable) {
             return NetworkUtils.isNetworkAvailableObservable()
                     .flatMap(aBoolean -> responseObservable)
                     .flatMap(new ReadListFunc(typeToken))
                     .onErrorResumeNext(ResponseErrorHandle.errorResumeFunc())
                     .subscribeOn(Schedulers.io())
                     .observeOn(AndroidSchedulers.mainThread());
         }

         // 读取列表数据
         private static class ReadListFunc<E> implements Func1<String, Observable<List<E>>> {

             private TypeToken<Response<List<E>>> typeToken;

             public ReadListFunc(TypeToken<Response<List<E>>> typeToken) {
                 this.typeToken = typeToken;
             }

            @Override
             public Observable<List<E>> call(String responseReply) {
                 Response<List<E>> response = new Gson().fromJson(responseReply, typeToken.getType());
                 if (response != null && response.code == ReturnCode.CODE_SUCCESS) {
                     return Observable.just(response.data);
                 } else {
                     return Observable.error(new Throwable());
                 }
             }
         }

     }

hope this to help you

**Comment by VictorAlbertos** [comment]
RxCache delegate this kind of responsibility to the current jolyglot provider.

In your case, it is Gson, so you will need to be aware about its limitations (configuration) when marshalling/unmarshalling data.

**Comment by llp** [comment]
public class GsonTSpeaker implements JolyglotGenerics {
    private final Gson gson;

    public GsonTSpeaker(Gson gson) {
        this.gson = gson;
    }

    public GsonTSpeaker() {
        this.gson = new Gson();
    }

    /**
     * {@inheritDoc}
     */
    @Override public String toJson(Object src) {
        return gson.toJson(src);
    }

    /**
     * {@inheritDoc}
     */
    @Override public String toJson(Object src, Type typeOfSrc) {
        return gson.toJson(src, typeOfSrc);
    }

    /**
     * {@inheritDoc}
     */
    @Override public <T> T fromJson(String json, Class<T> classOfT) throws RuntimeException {
        Type genType = classOfT.getGenericSuperclass();
        Type[] params = ((ParameterizedType) genType).getActualTypeArguments();
        return gson.fromJson(json, params[0]);
    }

    /**
     * {@inheritDoc}
     */
    @Override public <T> T fromJson(String json, Type typeOfT) throws RuntimeException {
        Type[] params = ((ParameterizedType) typeOfT).getActualTypeArguments();
        return gson.fromJson(json, params[0]);
    }

    /**
     * {@inheritDoc}
     */
    @Override public <T> T fromJson(File file, Class<T> classOfT) throws RuntimeException {
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader(file.getAbsoluteFile()));

            Type genType = classOfT.getGenericSuperclass();
            Type[] params = ((ParameterizedType) genType).getActualTypeArguments();

            T object =  gson.fromJson(reader, params[0]);
            reader.close();
            return object;
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException i) {}
            }
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override public <T> T fromJson(File file, Type typeOfT) throws RuntimeException {
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader(file.getAbsoluteFile()));
            Type[] params = ((ParameterizedType) typeOfT).getActualTypeArguments();
            T object =  gson.fromJson(reader, params[0]);
            reader.close();
            return object;
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException i) {}
            }
        }
    }

    @Override public GenericArrayType arrayOf(Type componentType) {
        return Types.arrayOf(componentType);
    }

    /**
     * {@inheritDoc}
     */
    @Override public ParameterizedType newParameterizedType(Type rawType, Type... typeArguments) {
        return Types.newParameterizedType(rawType, typeArguments);
    }

}

**Comment by vihuela** [comment]
There is another way
Use Explicit Type
```
public class BaseResponse<T> {
    public int code;
    public List<T> results;
}
```
```
public class ApiResponse extends BaseResponse<ApiResponse.FocusListItem> {

    public static class FocusListItem {
        。。。
    }
}
```
```
Observable<Reply<ApiResponse>> getFocusList(Observable<ApiResponse> observable, EvictProvider evictProvider);
```

**Comment by XiFanYin** [comment]
能不能来个中文版本的解决方案，本人就是遇到这个问题，不知道什么原因导致的

**Comment by JessYanCoding** [comment]
@XiFanYin 其实上面已经给出解决方案了, 很多人没看懂? 那我来总结一下, 之前的写法是, 自己创建一个实体类, 如 **User**, 然后使用 **BaseData< User >** 作为服务器返回的结果,
由于 **RxCache** 的一些限制, 导致 **BaseData** 中, 范型为 **T** 的字段 **data** 的实际类型没有作为缓存被正常保存到本地, 所以导致获取缓存时不能正常解析 **data** , 从而报错 `java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap`

现在的解决方案是, 稍微修改下之前定义的 **User**, 然后直接使用 **User** 作为服务器返回的结果, 这个解决方案对之前的代码改变较小, 也比较简单, 代码如下:

```java
public class BaseData<T> {
    private int code;
    private String msg;
    private T data;

    public T getData() {
        return data;
    }
}

只要继承 BaseData 并指定范型 (如果不是集合则继承 BaseData<User>) 即可, 其他都不用改
public class User extends BaseData<List<User>> {
    private int id;
    private String name;

    public int getId() {
        return id;
    }
}

Observable<User> getUsers(Observable<User> users, DynamicKey idLastUserQueried, EvictProvider evictProvider);

....

这是获取数据的方式
List<User> data = user.getData();
int id = data.get(0).getId();
```

**Comment by jonenet** [comment]
User会持有List<User> ,List<User> data中又存在User ，请问这种方式不会有问题吗？

**Comment by JessYanCoding** [comment]
@jonenet **User** 作为 **类** 的时候, 它即是 **BaseData** 又是 **JavaBean**，但当 **User** 被解析为对象进行操作时，只是把它看作是两种角色中的一个，这个方式在理解上可能比较绕，但是确不会对结果产生什么影响, 也是现在最简单的解决方案，只是需要注意 **User** 对象在不同的角色做不同的操作即可

如果你觉得这个方式不好理解，你也可以使用上面那个兄弟在 **User** 中定义一个内部类的方式，其实达到的目的都是一样的

**Comment by IurKwan** [comment]
直接用 T 作为缓存应该可以吧

**Comment by ghost** [comment]
@VictorAlbertos Hi, I meet the same issue with @ml-bright , and I also tried **JacksonSpeaker**, but **also got the error** `"java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to XXX.entity.HomeFloorBean" `, my response class is `BaseResponse<List<HomeFloorBean>>`, 
I am using `MVPArms` @JessYanCoding

**Comment by xilost** [comment]
@JessYanCoding 如果BaseData和user里有相同的参数，会出现无法解析的问题。UserInfo declares multiple JSON fields named gold

**Comment by BryceLee** [comment]
@PaulWoitaschek @xilost [#41]Don't Cache the BaseResponse, instead, use map operator to transform it to detail data model.

**Comment by foreverGoUp** [comment]
> User会持有List ,List data中又存在User ，请问这种方式不会有问题吗？

不会，你不要看类名套来套去的以为会有问题。类的定义只是定义了一种数据结构，只要能满足数据的存放需求，怎么嵌套都没关系。java也没限制同类互相嵌套。

**Comment by xilost** [comment]
@BryceLee 但是BaseResponse里的数据也是我需要的呢。
