### ISSUE TITLE
EvictProvider not evicting everything when used with Dynamic key

### ISSUE THREAD

**Issue by GeorgePetri** [VictorAlbertos/RxCache#77]
Hello,

This happnes on a cache provider that has an DynamicKey and a EvictProvider.
When called with new DynamicKey(page), new EvictProvider(true) it only evicts for the given page instead of evicting all pages.

Thanks.

**Comment by VictorAlbertos** [comment]
Please, review your configuration before submitting here this kind of issues. I can do nothing with your information. If you think that there is a bug, show it with a PR containing a test.

**Comment by GeorgePetri** [comment]
I am getting this in crashlytics. I didn't manage to isolate the issue in a test.
I am using gson for serialization, rxjava 1.2.5 .
Please take a look at the stacktrace.

`
Caused by java.util.ConcurrentModificationException
io.rx_cache.internal.cache.memory.apache.AbstractReferenceMap$ReferenceBaseIterator.checkMod (AbstractReferenceMap.java:808)
io.rx_cache.internal.cache.memory.apache.AbstractReferenceMap$ReferenceBaseIterator.nextEntry (AbstractReferenceMap.java:817)
io.rx_cache.internal.cache.memory.apache.AbstractReferenceMap$ReferenceKeySetIterator.next (AbstractReferenceMap.java:875)
io.rx_cache.internal.cache.Action.getKeysOnMemoryMatchingDynamicKey (Action.java:65)
io.rx_cache.internal.cache.EvictRecord.evictRecordsMatchingDynamicKey (EvictRecord.java:42)
io.rx_cache.internal.cache.TwoLayersCache.evictDynamicKey (TwoLayersCache.java:54)
io.rx_cache.internal.ProcessorProvidersBehaviour.clearKeyIfNeeded (ProcessorProvidersBehaviour.java:169)
io.rx_cache.internal.ProcessorProvidersBehaviour.access$400 (ProcessorProvidersBehaviour.java:36)
io.rx_cache.internal.ProcessorProvidersBehaviour$6.call (ProcessorProvidersBehaviour.java:144)
rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.call (OperatorOnErrorResumeNextViaFunction.java:53)
rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.call (OperatorOnErrorResumeNextViaFunction.java:50)
rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError (OperatorOnErrorResumeNextViaFunction.java:140)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onError (OnSubscribeMap.java:88)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:73)
retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext (OperatorMapResponseToBodyOrError.java:41)
retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext (OperatorMapResponseToBodyOrError.java:38)
retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request (RxJavaCallAdapterFactory.java:173)
rx.internal.producers.ProducerArbiter.setProducer (ProducerArbiter.java:126)
rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer (OperatorOnErrorResumeNextViaFunction.java:159)
rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer (OnSubscribeMap.java:102)
rx.Subscriber.setProducer (Subscriber.java:205)
retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call (RxJavaCallAdapterFactory.java:152)
retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call (RxJavaCallAdapterFactory.java:138)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:248)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:148)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:77)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:77)
rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request (ScalarSynchronousObservable.java:276)
rx.Subscriber.setProducer (Subscriber.java:211)
rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer (OnSubscribeMap.java:102)
rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer (OnSubscribeMap.java:102)
rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call (ScalarSynchronousObservable.java:138)
rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call (ScalarSynchronousObservable.java:129)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeDefer.call (OnSubscribeDefer.java:51)
rx.internal.operators.OnSubscribeDefer.call (OnSubscribeDefer.java:35)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OnSubscribeDefer.call (OnSubscribeDefer.java:51)
rx.internal.operators.OnSubscribeDefer.call (OnSubscribeDefer.java:35)
rx.Observable.unsafeSubscribe (Observable.java:10144)
rx.internal.operators.OperatorSubscribeOn$1.call (OperatorSubscribeOn.java:94)
rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call (CachedThreadScheduler.java:230)
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:55)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:428)
java.lang.Thread.run (Thread.java:761)`
