### ISSUE TITLE
useExpiredDataIfLoaderNotAvailable

### ISSUE THREAD

**Issue by fjzboy** [VictorAlbertos/RxCache#78]
Hi, 

I have set useExpiredDataIfLoaderNotAvailable true, and closed my network. when the data is expired, it throw an exception 
"throwable:io.rx_cache.RxCacheException: The Loader provided did not return any data and there is not data to load from the Cache xxxx".

**Comment by JessYanCoding** [comment]
Check whether the local cache exists

**Comment by VictorAlbertos** [comment]
Please, review your configuration before submitting here this kind of issues. I can do nothing with your information. If you think that there is a bug, show it with a PR containing a test.

**Comment by cnting** [comment]
I have the same question.

1. Open app,get url from net and save to cache file
2.Close app completely
3.Change phone system time to overdue
4.Open app again,notice cache file has been deleted
