### ISSUE TITLE
pom XML issue

### ISSUE THREAD

**Issue by ainesophaur** [VictorAlbertos/RxCache#8]
I'm not too familiar with jitpack's process but the POM downloaded using gradle is giving a syntax issue.

https://jitpack.io/com/github/VictorAlbertos/RxCache/0.4.9/RxCache-0.4.9.pom

Lines 20-22 should be removed.
```xml
...
  </dependencies>
</project>
</groupId>
`

**Comment by VictorAlbertos** [comment]
Hi.

I can't see any error in the pom xml generated file. 

So far, I've not found any error using gradle with Android Studio. Are you using IntellJ Idea, or some other ide which build with gradle?

If the error persists, you can open an issue on [jitpack's project](https://github.com/jitpack/jitpack.io) to know what could be the problem.
