### ISSUE TITLE
Prevent observable from getting evicted?

### ISSUE THREAD

**Issue by cordeirovs** [VictorAlbertos/RxCache#88]
Is there a way to prevent an observable from getting evicted if no data is returned from the server?

For example, each time the user refreshes a news feed (pull to refresh) `getRepository().getFeedPosts(tag, new EvictProvider(true));` gets called.
If the user suddently loses his connection to the internet and refreshes the feed again, no data gets returned from the server, the observable gets evicted and it returns the cached version (since I'm setting `useExpiredDataIfLoaderNotAvailable(true)` on the RxCache builder).

Again with no internet connection, if the user refreshes a second time, no cached data is available.
Is there a way to prevent that from happening?

Thanks

**Comment by VictorAlbertos** [comment]
I don't think that's possible. Precisely, this is the way you evict the data of some provider, by creating an observable that just throws. I admit this is not optimal, but if you want to use a more mature API which handles these scenarios properly, I recommend to you to use [ReactiveCache](https://github.com/VictorAlbertos/ReactiveCache)
