### ISSUE TITLE
annotationProcessor support 

### ISSUE THREAD

**Issue by alouanemed** [VictorAlbertos/RxCache#89]
I am doing a migration to the latest Android O and this error appeared after updating the sdk version: 

> Annotation processors must now be declared explicitly.  The following dependencies in the compile classpath are found to contain annotation processors.  Please add them to the annotationProcessor configuration.
    - compiler-1.6.8-2.x.jar
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with the previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

although there is a fix to overcome to this, can you do the same update with JakeWharton/butterknife#908

The fix
```

 javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
```

**Comment by VictorAlbertos** [comment]
Thanks for the info. Do you care to submit a PR?

**Comment by VictorAlbertos** [comment]
Feel free to reopen it if you care to submit a PR.
