### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by XelAlone** [VictorAlbertos/RxCache#9]
First of all, great work! A powerful library to apply together with Retrofit. 

However, do you really need so many dependencies? As an Android Developer, I always work on minimizing method count. As far as I'm concerned, it's unnecessary to import `Dagger` and `Guava`. These will cause growth of method count.

**Comment by VictorAlbertos** [comment]
Hi!

I don't think RxCache has too much dependencies.

Dagger dependency only add 50 methods.

And for Guava dependency -which is really huge (13.000 methods), you can remove it if you don't need RxCache evicts objects automatically before the application reaches its max heap memory (this is explained in the [docs](https://github.com/VictorAlbertos/RxCache)).
