### ISSUE TITLE
Can not use RxCache in my Project.

### ISSUE THREAD

**Issue by LCM-93** [VictorAlbertos/RxCache#90]
AS always show this logs when i build my project........

       Gradle sync failed: Could not find com.github.VictorAlbertos.RxCache:runtime:1.8.0-2.x.
	Required by:
	project :base
	Consult IDE log for more details (Help | Show Log)

**Comment by VictorAlbertos** [comment]
Did you solve the issue? Did you add?

```gradle
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by LCM-93** [comment]
Is my problem....
i am sure  add this  `maven { url "https://jitpack.io" }`  
but......
```
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
-_-\\
