### ISSUE TITLE
proguard rules

### ISSUE THREAD

**Issue by alouanemed** [VictorAlbertos/RxCache#94]
Here is my current progaurd file config for rxCache 2 : 

```
-dontwarn io.rx_cache2.internal.**
-keepclassmembers enum io.rx_cache2.Source { *; }
-keepclassmembernames class * { @io.rx_cache2.* <methods>; }
```

Progaurd output : 

Warning: io.rx_cache2.BrewJavaFile: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.BrewJavaFile: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.BrewJavaFile: can't find referenced class com.sun.tools.javac.util.List
Warning: io.rx_cache2.BrewJavaFile: can't find referenced class com.sun.tools.javac.util.List
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$MethodSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$TypeSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$MethodSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.util.Name
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.util.Name
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$MethodSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$TypeSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.util.List
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.util.List
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$MethodSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$MethodSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Type
com.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$VarSymbolcom.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.GetProvidersClass: can't find referenced class com.sun.tools.javac.code.Symbol$VarSymbol
Warning: io.rx_cache2.ProvidersClass$Method: can't find referenced class com.sun.tools.javac.code.Type
Warning: io.rx_cache2.ProvidersClass$Method: can't find referenced class com.sun.tools.javac.code.Type

**Comment by VictorAlbertos** [comment]
I don't use Proguard. But the current suggestion (README) given by other users did not suit you well?

```
-dontwarn io.rx_cache.internal.**
-keepclassmembers enum io.rx_cache.Source { *; }
```
