### ISSUE TITLE
It is possible to evict all group of pages?

### ISSUE THREAD

**Issue by hypeapps** [VictorAlbertos/RxCache#95]
@VictorAlbertos your library is awesome but I'm little confused about evicting all pages in group so I have question.

I have repository like this:
```
// this usecase request for most popular without evicting
override fun getMostPopular(page: Int): Single<MostPopularEntity> {
       return tvShowCacheProviders.getMostPopular(apiService.getMostPopular(pageableRequest.page, pageableRequest.size),
              DynamicKeyGroup("MP", "${page}"))
    }
// I think this usecase should evict all pages for key "MP"?
override fun getMostPopularWithUpdate(page: Int): Single<MostPopularEntity> {
        return tvShowCacheProviders.getMostPopularWithUpdate(apiService.getMostPopular(pageableRequest.page, pageableRequest.size),
                DynamicKeyGroup("MP", "${page}"), EvictDynamicKeyGroup(true))
    }
```
Both methods are `@LifeCache(duration = 30, timeUnit = TimeUnit.MINUTES)
`
My usecase is like that:
While I pull to refresh I'm calling `getMostPopularWithUpdate(page=1)` and I expect evict all pages in group and I think future calls of `getMostPopular(1,2,3 so on)` would come from network, not cache but in my example only `getMostPopularWithUpdate(page=1)` call evict and get fresh data.

So, it is possible to evict specific key of groups?

**Comment by VictorAlbertos** [comment]
Use `EvictProvider` instead of `EvictDynamicKeyGroup` if you want to evict the whole provider. You have a [complete set](https://github.com/VictorAlbertos/RxCache/blob/2.x/runtime/src/test/java/io/rx_cache2/internal/ProvidersDynamicsKeysRxCacheTest.java#L101) of tests which illustrate this behaviour. 

```java
override fun getMostPopularWithUpdate(page: Int): Single<MostPopularEntity> {
        return tvShowCacheProviders.getMostPopularWithUpdate(apiService.getMostPopular(pageableRequest.page, pageableRequest.size),
                DynamicKeyGroup("MP", "${page}"), EvictProvider(true))
    }
```
